version: "3.8"

services:
  yetkenya-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yetkenya-website
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=yet-kenya.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=yet-kenya.com
      - LETSENCRYPT_EMAIL=info@yet-kenya.com
    networks:
      - proxy

networks:
  proxy:
    external: true
